[theme]
base = "light"
primaryColor = "#1257a8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#eef1f5"
textColor = "#191d27"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
